apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:                  # zoznam manifestov - zdrojov,
  # ktoré sú súčasťou tejto aplikácie
  - ./bbm-project

commonLabels:               # značky priradené všetkým zdrojom tejto aplikácie
  app: bbm-project
