kind: Service
apiVersion: v1
metadata:
  name: m-nem-ambulance-ufe   #  určuje aj záznam DNS v rámci virtuálne siete klastra
spec:  
  selector:
    pod: m-nem-ambulance-ufe-label     # zhoduje sa s metadata.labels šablóny pod-u
  ports:
  - name: http
    protocol: TCP
    port: 80            
    targetPort: http    # viď meno portu v deployment.yaml
