apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata: 
  name: mar-ku-ambulance-ufe
spec:   
  module-uri: http://mar-ku-ambulance-ufe.wac-hospital/build/ambulance-list.esm.js
  navigation:
    - element: mar-ku-ambulance-wl-app
      path: mar-ku-ambulance-wl
      title: Zoznam čakajúcich MarKu
      details: Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii
      attributes:
        - name: api-uri
          value: /mar-ku-waiting-list-api
        - name: ambulance
          value: bobulova
  preload: false
  proxy: true
  hash-suffix: v1alpha1
