apiVersion: apps/v1
kind: Deployment
metadata:
  name: jb-ambulance-ufe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: jb-ambulance-ufe-label
  template:                    # šablóna pre vytvorenie replík podov
    metadata:
      labels:
        pod: jb-ambulance-ufe-label
    spec:
      containers:
        - name: jb-ambulance-ufe-container
          image: gh0stadian/ambulance-ufe:1.0.0-25
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              memory: "32M"
              cpu: "0.1"
            limits:
              memory: "320M"
              cpu: "0.3"
