apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata:
  name: tech-podolae-ambulance-ufe
spec:
  module-uri: http://tech-podolae-ambulance-ufe.wac-hospital/build/ambulance-list.esm.js
  navigation:
    - element: tech-podolae-ambulance-wl-app
      path: tech-podolae-ambulance-wl
      title: Zoznam čakajúcich tech-podolae
      details: Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii
      attributes:
        - name: base-path
          value: /ui/tech-podolae-ambulance-wl/
        - name: ambulance
          value: bobulova
  preload: false
  proxy: true
  hash-suffix: v1alpha1
