apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata:
  name: tech-podolae-ambulance-operations-ufe
spec:
  module-uri: http://tech-podolae-ambulance-operations-ufe.wac-hospital/build/ambulance-operations-tech-podolae.esm.js
  navigation:
    - element: tech-podolae-operation-list-app
      path: tech-podolae-operation-list
      title: Prehľad operácií tech-podolae
      details: Správa operácií a filtrovanie nad existujúcimi
      attributes:
        - name: base-path
          value: /ui/tech-podolae-operation-list/
        - name: api-uri
          value: /tech-podolae-ambulance-operations-api
  preload: false
  proxy: true
  hash-suffix: v1alpha2
