apiVersion: apps/v1
kind: Deployment
metadata:
  name: zy-ambulance-ufe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
        pod: zy-ambulance-ufe-label
  template:
    metadata:
      labels: 
        pod: zy-ambulance-ufe-label
    spec:
      containers:
      - name: zy-ambulance-ufe-container
        image: xzhan527/ambulance-ufe
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        resources:                   
            requests:               
                memory: "32M"
                cpu: "0.1"
            limits:
                memory: "320M"
                cpu: "0.3"
