apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata: 
  name: tl-team-ufe

spec:   
  module-uri: http://tl-team-ufe.wac-hospital/build/ambulance-list.esm.js
  navigation:
    - element: tl-ambulance-wl-app
      path: tl-ambulance-wl
      title: TL - Zoznam čakajúcich
      details: Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii
      attributes:
        - name: base-path
          value: /ui/tl-ambulance-wl/
        - name: ambulance
          value: bobulova
  preload: false
  proxy: true
  hash-suffix: v1alpha1
