apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:                  # zoznam manifestov - zdrojov,
                            # ktoré sú súčasťou tejto aplikácie
- deployment.yaml           # Zalezi na poradi
- service.yaml
- webcomponent.yaml

commonLabels:               # značky priradené všetkým zdrojom tejto aplikácie
  app: stesch-ambulance-list
