kind: Service
apiVersion: v1
metadata:
  name: mf-ambulance-ufe   
spec:  
  selector:
    pod: mf-ambulance-ufe-label    
  ports:
  - name: http
    protocol: TCP
    port: 80                    
    targetPort: http    