apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata: 
  name: t13-ambulance-t13
spec:   
  module-uri: http://t13-ambulance-t13.wac-hospital/build/ambulance-list.esm.js  
                     # module web komponentu pre tento mikroFE 
                     # - umiestnený v namespace wac-hospital
  navigation:
    - element: t13-ambulance-wl-list    # element, ktorý bude vložený na stránku 
                                    # pri navigácii na zoznam čakajúcich
      path: t13-ambulance-wl      # cesta, ktora sa zobrazi v address bare v prehliadaci, ked bude tento mikroFE aktívny
      title: Zoznam čakajúcich t13      # názov mikro aplikácie
      details: Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii
      attributes:                   
        - name: base-path
          value: /ui/t13-ambulance-wl/
        - name: ambulance
          value: bobulova
  preload: false                    # určuje, či má byť web komponent načítaný spolu s hlavnou stránkou
  proxy: true                       # pre komponenty v rámci klastra, neprístupné na verejnej sieti 
                                    # musí byť táto hodnota nastavená na true 
  hash-suffix: v1alpha1             # voliteľný suffix pre načítanie modulu web komponentu - jeho zmenou 
                                    # sa mení názov URL pre modul a tým je možné predísť problémom 
                                    # s verziami vo vyrovnávacích pamätiach
