apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata:
  name: pirky-ambulance-ufe
spec:
  module-uri: http://pirky-ambulance-ufe.wac-hospital/build/ambulance-list.esm.js
  navigation:
    - element: pirky-ambulance-wl-app
      path: pirky-ambulance-wl
      title: Zoznam čakajúcich
      details: Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii
      attributes:
        - name: base-path
          value: /pirky-ambulance-wl/
        - name: ambulance
          value: bobulova
  preload: false
  proxy: true
  hash-suffix: v1alpha2
