apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata: 
  name: kk-ambulance-ufe
spec:   
  module-uri: http://kk-ambulance-ufe.wac-hospital/build/kk-bed-management-ufe.esm.js
  navigation:
    - element: kk-app
      path: kk-beds
      title: Správa lôžkovej časti
      details: Spravuje priradenie pacientov ku lôžkam pre oddelenie v nemocnici
      attributes:
        - name: base-path
          value: /ui/kk-beds/
        - name: api-uri
          value: /departments-webapi
  preload: false
  proxy: true
  hash-suffix: v1alpha2
