apiVersion: apps/v1
kind: Deployment
metadata:
  name: fa-ambulance-ufe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
        pod: fa-ambulance-ufe-label
  template:
    metadata:
      labels:
        pod: fa-ambulance-ufe-label
    spec:
      containers:
      - name: fa-ambulance-ufe-container
        image: pumec/ambulance-ufe:1.0.0-25
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        resources:
            requests:
                memory: "32M"
                cpu: "0.1"
            limits:
                memory: "320M"
                cpu: "0.3"
