apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata:
  name: fa-ambulance-ufe
spec:
  module-uri: http://fa-ambulance-ufe.wac-hospital/build/ambulance-list.esm.js
  navigation:
    - element: fa-ambulance-wl-app
      path: fa-ambulance-wl
      title: Zoznam čakajúcich msevcik
      details: Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii
      attributes:
        - name: api-uri
          value: /fa-ambulance-wl/
        - name: ambulance
          value: bobulova
  preload: false
  proxy: true
  hash-suffix: v1alpha1
