apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../_msevcik_demo
  - ../../pc_ambulance
  - ../../mf-ambulance
  - ../../md_ambulance
  - ../../hoka-ambulance
  - ../../mar-ku-ambulance
  - ../../jm-lm-ambulance
  - ../../xholubov_ambulance
  - ../../hoka-ambulance
  - ../../adp-team
  - ../../ij-ambulance
  - ../../pirky
#  - ../../ll-ambulance

namespace: wac-hospital
