apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata:
  name: hianikova-ambulance-ufe
spec:
  module-uri: http://hianikova-ambulance-ufe.wac-hospital/build/ambulance-list.esm.js
  navigation:
    - element: hianikova-ambulance-wl-app
      path: hianikova-ambulance-wl
      title: Zoznam čakajúcich hianikova
      details: Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii
      attributes:
        - name: base-path
          value: /ui/hianikova-ambulance-wl/
        - name: ambulance
          value: bobulova
  preload: false
  proxy: true
  hash-suffix: v1alpha2
